### ISSUE TITLE
[BUG] {검색 필터링 오류}

### ISSUE THREAD

**Issue by moolmin** [100-hours-a-week/5-team-ark-connectrip-fe#49]
### 버그 현상 설명

{버그 현상을 설명해주세요.}
검색창에 입력된 값이 포함되어있지 않은 게시글도 필터링됩니다.

---

### 발생 과정

{ 버그를 발생 시키는 행동 과정을 적어주세요.

1. 동행탭 이동
2. 검색창에 '아' 검색
3. '멋있는 데이비드' 게시글이 필터링됨

---

### 예상 대책

{예상되는 대책을 적어주세요. 없다면 없다고 적어주세요.}
검색로직 수정

---

### 스크린샷

{버그 발생 화면을 스크린샷으로 남겨주세요.}

<img width="790" alt="Screenshot 2024-08-28 at 10 45 12 AM" src="https://github.com/user-attachments/assets/d2ef24fe-0665-4506-9192-bde1e3d76275">
---

### 기타 주석

{끝으로 남기고 싶은 기타 주석을 적어주세요. 없다면 지워주세요.}

**Comment by sen2y** [comment]
제목과 게시글 내용 중 검색어와 겹치는 경우 검색결과로 출력됩니다 :> 
남겨주신 게시글의 경우, 내용에 좋"아"용~ 과 검색어 "아" 가 일치하여 검색결과로 출력되었습니다~
