### ISSUE TITLE
[BUG] {비로그인 상태로 페이지 이동할때 로딩이슈}

### ISSUE THREAD

**Issue by carter468** [100-hours-a-week/5-team-ark-connectrip-fe#94]
### 버그 현상 설명

비로그인 상태로 게시물이랑 메뉴 돌아다니면 홈화면 이동할때 무한로딩 걸림

---

### 발생 과정

1. 비로그인 상태로 게시물도 눌러보고 하단 메뉴 이동 돌아다니다가 다시 홈화면갈때 발생

---

### 예상 대책

발생원인파악

---

### 스크린샷

https://github.com/user-attachments/assets/cd181419-990f-4f3e-bf95-08f0afe94e4d

**Comment by sen2y** [comment]
해결완료입니다. 좋은 의견 감사합니다. :>
